### ISSUE TITLE
Building samples from FlaDE-TypeError: Unregistered type : dv::Frame

### ISSUE THREAD

**Issue by AlexDDING** [KugaMaxx/cocoa-flade#1]
When I run the scripts "build.py" , it failed to build samples from FlaDE.
TypeError: Unable to convert function return value to a Python type, Unregistered type : dv::Frame.
![ss](https://github.com/user-attachments/assets/3130153e-30dd-4dd8-a115-6fe556466e7e)

**Comment by Gaozhch0204** [comment]
hello, did you solve this problem, please let me know, appreciate it!

**Comment by AlexDDING** [comment]
> hello, did you solve this problem, please let me know, appreciate it!

I have resolved the issue. To ensure the script executes correctly, please follow the steps outlined below:

- Ensure that your g++ version is greater than 10.
- Delete CMake cache file and build directory.
- Upgrade pybind11.
- Install `dv_toolkit`.
- Confirm that all dependencies are installed correctly, with particular attention to the successful build of the `dv_toolkit` wheel.

**Comment by Gaozhch0204** [comment]
> > hello, did you solve this problem, please let me know, appreciate it!
> 
> I have resolved the issue. To ensure the script executes correctly, please follow the steps outlined below:
> 
> * Ensure that your g++ version is greater than 10.
> * Delete CMake cache file and build directory.
> * Upgrade pybind11.
> * Install `dv_toolkit`.
> * Confirm that all dependencies are installed correctly, with particular attention to the successful build of the `dv_toolkit` wheel.

thank you for your help, I really appreciate it, but when I install dv_toolkit, it failed, what's the reason
 note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dv_toolkit
  Running setup.py clean for dv_toolkit
Failed to build dv_toolkit
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (dv_toolkit)

**Comment by Gaozhch0204** [comment]
> > > hello, did you solve this problem, please let me know, appreciate it!
> > 
> > 
> > I have resolved the issue. To ensure the script executes correctly, please follow the steps outlined below:
> > 
> > * Ensure that your g++ version is greater than 10.
> > * Delete CMake cache file and build directory.
> > * Upgrade pybind11.
> > * Install `dv_toolkit`.
> > * Confirm that all dependencies are installed correctly, with particular attention to the successful build of the `dv_toolkit` wheel.
> 
> thank you for your help, I really appreciate it, but when I install dv_toolkit, it failed, what's the reason note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for dv_toolkit Running setup.py clean for dv_toolkit Failed to build dv_toolkit ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (dv_toolkit)

<img width="728" alt="Image" src="https://github.com/user-attachments/assets/d9f09ed3-61c4-46dd-84e2-3ab951209272" />

> > hello, did you solve this problem, please let me know, appreciate it!
> 
> I have resolved the issue. To ensure the script executes correctly, please follow the steps outlined below:
> 
> * Ensure that your g++ version is greater than 10.
> * Delete CMake cache file and build directory.
> * Upgrade pybind11.
> * Install `dv_toolkit`.
> * Confirm that all dependencies are installed correctly, with particular attention to the successful build of the `dv_toolkit` wheel.

<img width="728" alt="Image" src="https://github.com/user-attachments/assets/a473ccc1-1427-4cbb-90ce-2b67ebf48250" />

**Comment by KugaMaxx** [comment]
Hi, @maonanzhi . Please provide the whole error log info about "ERROR: Failed to build installable wheels for some pyproject.toml based projects (dv_toolkit)" so that I may help you to solve. ;)

**Comment by Gaozhch0204** [comment]
> Hi, [@maonanzhi](https://github.com/maonanzhi) . Please provide the whole error log info about "ERROR: Failed to build installable wheels for some pyproject.toml based projects (dv_toolkit)" so that I may help you to solve. ;)

```bash
(cca3.8) zane@zane-virtual-machine:~/PycharmProjects/PythonProject/cocoa-flade$ pip install external/dv-toolkit/.
Processing ./external/dv-toolkit
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.24 in /home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages (from dv_toolkit==0.1.2) (1.24.4)
Requirement already satisfied: dv_processing>=1.7 in /home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages (from dv_toolkit==0.1.2) (1.7.9)
Requirement already satisfied: plotly>=5.17 in /home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages (from dv_toolkit==0.1.2) (6.0.0)
Requirement already satisfied: matplotlib>=3.7 in /home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages (from dv_toolkit==0.1.2) (3.7.5)
Requirement already satisfied: contourpy>=1.0.1 in /home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages (from matplotlib>=3.7->dv_toolkit==0.1.2) (1.1.1)
Requirement already satisfied: cycler>=0.10 in /home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages (from matplotlib>=3.7->dv_toolkit==0.1.2) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages (from matplotlib>=3.7->dv_toolkit==0.1.2) (4.56.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages (from matplotlib>=3.7->dv_toolkit==0.1.2) (1.4.7)
Requirement already satisfied: packaging>=20.0 in /home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages (from matplotlib>=3.7->dv_toolkit==0.1.2) (24.2)
Requirement already satisfied: pillow>=6.2.0 in /home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages (from matplotlib>=3.7->dv_toolkit==0.1.2) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages (from matplotlib>=3.7->dv_toolkit==0.1.2) (3.1.4)
Requirement already satisfied: python-dateutil>=2.7 in /home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages (from matplotlib>=3.7->dv_toolkit==0.1.2) (2.9.0.post0)
Requirement already satisfied: importlib-resources>=3.2.0 in /home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages (from matplotlib>=3.7->dv_toolkit==0.1.2) (6.4.5)
Requirement already satisfied: narwhals>=1.15.1 in /home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages (from plotly>=5.17->dv_toolkit==0.1.2) (1.29.0)
Requirement already satisfied: zipp>=3.1.0 in /home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages (from importlib-resources>=3.2.0->matplotlib>=3.7->dv_toolkit==0.1.2) (3.20.2)
Requirement already satisfied: six>=1.5 in /home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages (from python-dateutil>=2.7->matplotlib>=3.7->dv_toolkit==0.1.2) (1.17.0)
Building wheels for collected packages: dv_toolkit
  Building wheel for dv_toolkit (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build/lib.linux-x86_64-cpython-38/dv_toolkit
      copying python/src/dv_toolkit/__init__.py -> build/lib.linux-x86_64-cpython-38/dv_toolkit
      creating build/lib.linux-x86_64-cpython-38/dv_toolkit/plot
      copying python/src/dv_toolkit/plot/player.py -> build/lib.linux-x86_64-cpython-38/dv_toolkit/plot
      copying python/src/dv_toolkit/plot/__init__.py -> build/lib.linux-x86_64-cpython-38/dv_toolkit/plot
      creating build/lib.linux-x86_64-cpython-38/dv_toolkit/plot/tools
      copying python/src/dv_toolkit/plot/tools/__init__.py -> build/lib.linux-x86_64-cpython-38/dv_toolkit/plot/tools
      copying python/src/dv_toolkit/plot/tools/func.py -> build/lib.linux-x86_64-cpython-38/dv_toolkit/plot/tools
      copying python/src/dv_toolkit/plot/tools/mp_player.py -> build/lib.linux-x86_64-cpython-38/dv_toolkit/plot/tools
      copying python/src/dv_toolkit/plot/tools/go_player.py -> build/lib.linux-x86_64-cpython-38/dv_toolkit/plot/tools
      running build_ext
      CMake Error: The source directory "/home/zane/PycharmProjects/PythonProject/cocoa-flade/external/dv-toolkit" does not appear to contain CMakeLists.txt.
      Specify --help for usage, or press the help button on the CMake GUI.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/zane/PycharmProjects/PythonProject/cocoa-flade/external/dv-toolkit/setup.py", line 188, in <module>
          setup(
        File "/home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
        File "/home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
        File "/home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
        File "/home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages/setuptools/command/bdist_wheel.py", line 398, in run
          self.run_command("build")
        File "/home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 98, in run
          _build_ext.run(self)
        File "/home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 476, in build_extensions
          self._build_extensions_serial()
        File "/home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 502, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/zane/PycharmProjects/PythonProject/cocoa-flade/external/dv-toolkit/setup.py", line 132, in build_extension
          ret = subprocess.run(["cmake", ext.sourcedir, *cmake_args], cwd=build_temp, check=True)
        File "/home/zane/anaconda3/envs/cca3.8/lib/python3.8/subprocess.py", line 516, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['cmake', '/home/zane/PycharmProjects/PythonProject/cocoa-flade/external/dv-toolkit', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/zane/PycharmProjects/PythonProject/cocoa-flade/external/dv-toolkit/build/lib.linux-x86_64-cpython-38/dv_toolkit/lib', '-DPYTHON_EXECUTABLE=/home/zane/anaconda3/envs/cca3.8/bin/python', '-DCMAKE_BUILD_TYPE=Release', '-DPython3_EXECUTABLE=/home/zane/anaconda3/envs/cca3.8/bin/python', '-DTOOLKIT_ENABLE_SAMPLES=OFF', '-DTOOLKIT_ENABLE_PYTHON=ON']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dv_toolkit
  Running setup.py clean for dv_toolkit
Failed to build dv_toolkit
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (dv_toolkit)
```
above is the whole error log info, thank you

**Comment by Gaozhch0204** [comment]
> Hi, [@maonanzhi](https://github.com/maonanzhi) . Please provide the whole error log info about "ERROR: Failed to build installable wheels for some pyproject.toml based projects (dv_toolkit)" so that I may help you to solve. ;)

if there is possible, can I get your wechat to discuss about this problem, appreciate it

**Comment by maonanzhi** [comment]
Zane
***@***.***



&nbsp;
if there is possible, can I get your wechat to discuss about this problem, appreciate it！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KugaMaxx/cocoa-flade"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年3月6日(星期四) 中午11:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [KugaMaxx/cocoa-flade] Building samples from FlaDE-TypeError: Unregistered type : dv::Frame (Issue #1)



   
Hi, @maonanzhi . Please provide the whole error log info about "ERROR: Failed to build installable wheels for some pyproject.toml based projects (dv_toolkit)" so that I may help you to solve. ;)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;
  KugaMaxx left a comment (KugaMaxx/cocoa-flade#1)
 
Hi, @maonanzhi . Please provide the whole error log info about "ERROR: Failed to build installable wheels for some pyproject.toml based projects (dv_toolkit)" so that I may help you to solve. ;)

**Comment by KugaMaxx** [comment]
@maonanzhi Based on your error log:

```
CMake Error: The source directory "/home/zane/PycharmProjects/PythonProject/cocoa-flade/external/dv-toolkit" does not appear to contain CMakeLists.txt.
```

It seems that the `dv-toolkit` package has not been correctly initialized and is empty now. Please navigate to `<file_path>/cocoa-flade/` and run the following command first:

```
git submodule update --init --recursive
```

Make sure this step completes without any errors.

After that, you can rerun `bash setup.sh`.

**Comment by Gaozhch0204** [comment]
> [@maonanzhi](https://github.com/maonanzhi) Based on your error log:
> 
> ```
> CMake Error: The source directory "/home/zane/PycharmProjects/PythonProject/cocoa-flade/external/dv-toolkit" does not appear to contain CMakeLists.txt.
> ```
> 
> It seems that the `dv-toolkit` package has not been correctly initialized and is empty now. Please navigate to `<file_path>/cocoa-flade/` and run the following command first:
> 
> ```
> git submodule update --init --recursive
> ```
> 
> Make sure this step completes without any errors.
> 
> After that, you can rerun `bash setup.sh`.

I really appreciate for your reply, I already solve this problem
(cca3.8) zane@zane-virtual-machine:~/PycharmProjects/PythonProject/cocoa-flade$ pip install external/dv-toolkit/.
Processing ./external/dv-toolkit
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.24 in /home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages (from dv_toolkit==0.1.2) (1.24.4)
Requirement already satisfied: dv_processing>=1.7 in /home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages (from dv_toolkit==0.1.2) (1.7.9)
Requirement already satisfied: plotly>=5.17 in /home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages (from dv_toolkit==0.1.2) (6.0.0)
Requirement already satisfied: matplotlib>=3.7 in /home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages (from dv_toolkit==0.1.2) (3.7.5)
Requirement already satisfied: contourpy>=1.0.1 in /home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages (from matplotlib>=3.7->dv_toolkit==0.1.2) (1.1.1)
Requirement already satisfied: cycler>=0.10 in /home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages (from matplotlib>=3.7->dv_toolkit==0.1.2) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages (from matplotlib>=3.7->dv_toolkit==0.1.2) (4.56.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages (from matplotlib>=3.7->dv_toolkit==0.1.2) (1.4.7)
Requirement already satisfied: packaging>=20.0 in /home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages (from matplotlib>=3.7->dv_toolkit==0.1.2) (24.2)
Requirement already satisfied: pillow>=6.2.0 in /home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages (from matplotlib>=3.7->dv_toolkit==0.1.2) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages (from matplotlib>=3.7->dv_toolkit==0.1.2) (3.1.4)
Requirement already satisfied: python-dateutil>=2.7 in /home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages (from matplotlib>=3.7->dv_toolkit==0.1.2) (2.9.0.post0)
Requirement already satisfied: importlib-resources>=3.2.0 in /home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages (from matplotlib>=3.7->dv_toolkit==0.1.2) (6.4.5)
Requirement already satisfied: narwhals>=1.15.1 in /home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages (from plotly>=5.17->dv_toolkit==0.1.2) (1.29.0)
Requirement already satisfied: zipp>=3.1.0 in /home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages (from importlib-resources>=3.2.0->matplotlib>=3.7->dv_toolkit==0.1.2) (3.20.2)
Requirement already satisfied: six>=1.5 in /home/zane/anaconda3/envs/cca3.8/lib/python3.8/site-packages (from python-dateutil>=2.7->matplotlib>=3.7->dv_toolkit==0.1.2) (1.17.0)
Building wheels for collected packages: dv_toolkit
  Building wheel for dv_toolkit (setup.py) ... done
  Created wheel for dv_toolkit: filename=dv_toolkit-0.1.2-cp38-cp38-linux_x86_64.whl size=429031 sha256=22a31b0b8d390f90811c90617189f3f7dff75208d2178e7aba06f52739fe9aa9
  Stored in directory: /home/zane/.cache/pip/wheels/20/61/33/d5add2469548938ed165488c5f4548064697903a7916497904
Successfully built dv_toolkit
Installing collected packages: dv_toolkit
  Attempting uninstall: dv_toolkit
    Found existing installation: dv_toolkit 0.1.2
    Uninstalling dv_toolkit-0.1.2:
      Successfully uninstalled dv_toolkit-0.1.2
Successfully installed dv_toolkit-0.1.2




but when I run build.py, it failed to build samples from FlaDE
(cca3.8) zane@zane-virtual-machine:~/PycharmProjects/PythonProject/cocoa-flade/data/FlaDE/scripts$ python build.py 
Building samples from FlaDE...
  0%|                                                                                                                                                                                               | 0/25 [00:00<?, ?it/s]
TypeError: Unregistered type : dv::Frame

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "build.py", line 89, in <module>
    process(file, denoise=False)
  File "build.py", line 46, in process
    clip_index, latest_frame = 0, data.frames().at(0)
TypeError: Unable to convert function return value to a Python type! The signature was
        (self: dv_toolkit.lib._lib_toolkit.FrameStorage, index: int) -> dv::Frame

**Comment by KugaMaxx** [comment]
At present, this issue does exist. If you want to use our FlaDE dataset, you can temporarily download it directly from this [link](https://drive.usercontent.google.com/download?id=1orF3i8lhT26fixFRavtphPOqgD4p4lyB&authuser=0) without running `build. py`.

Otherwise, if you want to run `samples/bec_svm/demo.py`, you can first create `data/` folder and unzip FlaDE into this folder, like `data/FlaDE`. Then comments line 44 in `samples/bec_svm/demo.py`.

``` python
# parse samples
sample = {
    'events': self._parse_events_from(data['events']),
    # 'frames': self._parse_frames_from(data['frames']),
}
```

![Image](https://github.com/user-attachments/assets/1d165f14-3ac1-49cd-a75a-2e469fde7697)

**Comment by Gaozhch0204** [comment]
> At present, this issue does exist. If you want to use our FlaDE dataset, you can temporarily download it directly from this [link](https://drive.usercontent.google.com/download?id=1orF3i8lhT26fixFRavtphPOqgD4p4lyB&authuser=0) without running `build. py`.
> 
> Otherwise, if you want to run `samples/bec_svm/demo.py`, you can first create `data/` folder and unzip FlaDE into this folder, like `data/FlaDE`. Then comments line 44 in `samples/bec_svm/demo.py`.
> 
> # parse samples
> sample = {
>     'events': self._parse_events_from(data['events']),
>     # 'frames': self._parse_frames_from(data['frames']),
> }
> ![Image](https://github.com/user-attachments/assets/1d165f14-3ac1-49cd-a75a-2e469fde7697)

I already download dataset and did what you said above, it still have this problem
(cca3.8) zane@zane-virtual-machine:~/PycharmProjects/PythonProject/cocoa-flade/samples/bec_svm$ python demo.py 
Training...
Traceback (most recent call last):
  File "demo.py", line 25, in <module>
    for i, (sample, target) in enumerate(data_loader):
  File "/home/zane/PycharmProjects/PythonProject/cocoa-flade/samples/bec_svm/dataset.py", line 39, in __getitem__
    data = reader.loadData()
RuntimeError: /usr/include/dv-processing/io/simplefile.hpp(172): dv::io::SimpleFile::SimpleFile(const std::filesystem::__cxx11::path&, dv::io::ModeFlags, dv::io::WriteFlags, size_t)()
FileError: Failed to open file with error: 'No such file or directory'. - Error info: File: /home/zane/PycharmProjects/PythonProject/cocoa-flade/samples/bec_svm/../../data/FlaDE/samples/F01_c05/denoised_clips/00601.aedat4


<img width="742" alt="Image" src="https://github.com/user-attachments/assets/beb871fb-f9ba-4812-9029-08a9f3b1ef0c" />

**Comment by KugaMaxx** [comment]
Based on your error 'No such file or directory', you need to make sure that `data/samples/` is not empty.
